# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=4, null=True, verbose_name='Estatura')),
                ('weight', models.CharField(blank=True, max_length=7, null=True, verbose_name='Peso')),
                ('waist_circumference', models.CharField(blank=True, max_length=7, null=True, verbose_name='Circunferencia de la cintura')),
                ('resting_heart_rate', models.CharField(blank=True, max_length=7, null=True, verbose_name='Frecuencia cardiaca en reposo')),
                ('blood_pressure', models.CharField(blank=True, max_length=7, null=True, verbose_name='Presión arterial')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
