# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physical_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='presión arterial'),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='height',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='estatura'),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='resting_heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='frecuencia cardiaca en reposo'),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='alumno'),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='waist_circumference',
            field=models.FloatField(blank=True, max_length=7, null=True, verbose_name='circunferencia de la cintura'),
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='weight',
            field=models.FloatField(blank=True, max_length=7, null=True, verbose_name='peso'),
        ),
    ]
