# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_record', '0002_auto_20171203_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalrecord',
            name='height',
            field=models.FloatField(default=None, max_length=4, verbose_name='estatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physicalrecord',
            name='weight',
            field=models.FloatField(default=1.7, max_length=7, verbose_name='peso'),
            preserve_default=False,
        ),
    ]
