# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_nutrition_nutrition_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrition',
            options={'ordering': ['-create_date']},
        ),
    ]
