# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=10, unique=True, verbose_name='Boleta')),
                ('career', models.CharField(choices=[('AI', 'Administración Industrial'), ('II', 'Ingeniería Industrial'), ('IT', 'Ingeniería en Transporte'), ('IN', 'Ingeniería en Informática'), ('CI', 'Ciencias de la Informática')], max_length=2, verbose_name='Carrera')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, verbose_name='Semestre')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('first_surname', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('second_surname', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telephone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('card_code', models.CharField(max_length=11, verbose_name='Código Tarjeta')),
            ],
            options={
                'ordering': ['first_surname', 'second_surname'],
            },
        ),
    ]
