# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='card_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Código Tarjeta'),
        ),
    ]
