# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pase_lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha']},
        ),
    ]
