# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta', models.CharField(max_length=10, unique=True, verbose_name='Boleta')),
                ('carrera', models.CharField(choices=[('AI', 'Administración Industrial'), ('II', 'Ingeniería Industrial'), ('IT', 'Ingeniería en Transporte'), ('IN', 'Ingeniería en Informática'), ('CI', 'Ciencias de la Informática')], max_length=2, verbose_name='Carrera')),
                ('semestre', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, verbose_name='Semestre')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('estatura', models.CharField(blank=True, max_length=4, null=True, verbose_name='Estatura')),
                ('peso', models.CharField(blank=True, max_length=7, null=True, verbose_name='Peso')),
                ('circunferencia_cintura', models.CharField(blank=True, max_length=7, null=True, verbose_name='Circunferencia de la cintura')),
                ('frecuencia_reposo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Frecuencia cardiaca en reposo')),
                ('presion_arterial', models.CharField(blank=True, max_length=7, null=True, verbose_name='Presión arterial')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
