# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20170812_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnodatosfisicos',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Datos Físicos'},
        ),
        migrations.AlterModelOptions(
            name='alumnodatospersonales',
            options={'ordering': ['apellido_paterno'], 'verbose_name_plural': 'Datos Personales'},
        ),
    ]
